---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: {{ $.Release.Name | quote }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $.Chart.Name | quote }}
        app.kubernetes.io/instance: {{ $.Release.Name | quote }}
      containers:
        - name: "java"
          image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 80
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $.Chart.Name | quote }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  replicas: {{ $.Values.replicaCount }}
